https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true
Import TensorFlow (tf) and get the version of tf

In [1]:
from time import time

st = time()

import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

print(f"Time elapsed: {time()-st: .2f}")

<module 'tensorflow._api.v2.version' from 'E:\\Anaconda_install\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>
Time elapsed:  1.01


Creating Tensors

In [2]:
st = time()

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(f"Time elapsed: {time()-st: .2f}")

Time elapsed:  99.89


Rank/Degree of Tensors

In [3]:
st = time()

rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

print(f"Time elapsed: {time()-st: .2f}")

Time elapsed:  0.01


In [4]:
st = time()

print(tf.rank(rank2_tensor))

print(f"Time elapsed: {time()-st: .2f}")

tf.Tensor(2, shape=(), dtype=int32)
Time elapsed:  0.00


Shape of Tensors

In [5]:
st = time()

print(rank2_tensor.shape)

print(f"Time elapsed: {time()-st: .2f}")

(2, 2)
Time elapsed:  0.00


Changing Shape

In [6]:
st = time()

tensor1 = tf.ones([1, 2, 3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]

# The numer of elements in the reshaped tensor MUST match the number in the original    

print(f"Time elapsed: {time()-st: .2f}")

Time elapsed:  0.01


In [7]:
st = time()

print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

print(f"Time elapsed: {time()-st: .2f}")

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
Time elapsed:  0.00


Slicing Tensors

In [8]:
st = time()

# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 

print(tf.rank(tensor))

print(tensor.shape)

print(f"Time elapsed: {time()-st: .2f}")

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
Time elapsed:  0.01


In [9]:
st = time()

# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

print(f"Time elapsed: {time()-st: .2f}")

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
Time elapsed:  0.00
