https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [2]:
import numpy as np

In [3]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [4]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [5]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [7]:
a = np.array(['a', 'b', 'b', 'c', 'a'])

u, indices = np.unique(a, return_index=True)

print(u)
print(indices)

a[indices]

['a' 'b' 'c']
[0 1 3]


array(['a', 'b', 'c'], dtype='<U1')

In [10]:
a = np.array([1, 2, 6, 4, 2, 3, 2])

u, indices = np.unique(a, return_inverse=True)

print(u)
print(indices)
print(u[indices])

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]


In [12]:
a = np.array([1, 2, 6, 4, 2, 3, 2])

values, counts = np.unique(a, return_counts=True)

print(values)
print(counts)
np.repeat(values, counts)

[1 2 3 4 6]
[1 3 1 1 1]


array([1, 2, 2, 2, 3, 4, 6])

geeksforgeeks.org/python-get-unique-values-list/

In [13]:
import numpy as np
 
# function to get unique values
def unique(list1):
    x = np.array(list1)
    print(np.unique(x))
      
# driver code
list1 = [10, 20, 10, 30, 40, 40]
print("the unique values from 1st list is")
unique(list1)
 
list2 =[1, 2, 1, 1, 3, 4, 3, 3, 5]
print("\nthe unique values from 2nd list is")
unique(list2)

the unique values from 1st list is
[10 20 30 40]

the unique values from 2nd list is
[1 2 3 4 5]


https://pandas.pydata.org/docs/reference/api/pandas.unique.html

In [14]:
import pandas as pd

In [15]:
pd.unique(pd.Series([2, 1, 3, 3]))

array([2, 1, 3], dtype=int64)

In [17]:
print(pd.Series([2] + [1] * 5))

pd.unique(pd.Series([2] + [1] * 5))

0    2
1    1
2    1
3    1
4    1
5    1
dtype: int64


array([2, 1], dtype=int64)

In [19]:
print(pd.Series([pd.Timestamp("20160101"), pd.Timestamp("20160101")]))

pd.unique(pd.Series([pd.Timestamp("20160101"), pd.Timestamp("20160101")]))

0   2016-01-01
1   2016-01-01
dtype: datetime64[ns]


array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [20]:
pd.unique(list("baabc"))

array(['b', 'a', 'c'], dtype=object)

In [21]:
pd.unique([("a", "b"), ("b", "a"), ("a", "c"), ("b", "a")])

array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)

https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html?highlight=unique#pandas.Series.unique

In [22]:
pd.Series([2, 1, 3, 3], name='A').unique()

array([2, 1, 3], dtype=int64)

In [23]:
a = pd.Series([pd.Timestamp('2016-01-01') for _ in range(3)])
print(a)
a.unique()

0   2016-01-01
1   2016-01-01
2   2016-01-01
dtype: datetime64[ns]


array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [24]:
a = pd.Series([pd.Timestamp('2016-01-01', tz='US/Eastern')
           for _ in range(3)])
print(a)
a.unique()

0   2016-01-01 00:00:00-05:00
1   2016-01-01 00:00:00-05:00
2   2016-01-01 00:00:00-05:00
dtype: datetime64[ns, US/Eastern]


<DatetimeArray>
['2016-01-01 00:00:00-05:00']
Length: 1, dtype: datetime64[ns, US/Eastern]

In [25]:
a = pd.Series(pd.Categorical(list('baabc')))
print(a)
a.unique()

0    b
1    a
2    a
3    b
4    c
dtype: category
Categories (3, object): ['a', 'b', 'c']


['b', 'a', 'c']
Categories (3, object): ['b', 'a', 'c']

In [26]:
a = pd.Series(pd.Categorical(list('baabc'), categories=list('abc'),
                         ordered=True))
print(a)
a.unique()

0    b
1    a
2    a
3    b
4    c
dtype: category
Categories (3, object): ['a' < 'b' < 'c']


['b', 'a', 'c']
Categories (3, object): ['a' < 'b' < 'c']