**def dynamic_stitch(indices, data, name=None):**

  Args:
  
    indices: A list of at least 1 `Tensor` objects with type `int32`.
    它是具有至少1个张量且每个张量具有dtype int32的张量的列表
    
    data: A list with the same length as `indices` of `Tensor` objects with the same type.
    它是具有与索引相同长度的张量的列表
    
    name: A name for the operation (optional).

  Returns:
  
    A `Tensor`. Has the same type as `data`.

## Example 1

In [1]:
import tensorflow as tf 
from time import time

In [2]:
indices = [[0, 1, 5], [2, 4, 3, 6]] 
data = [[1, 2, 3], [4, 5, 6, 7]] 

In [3]:
indices

[[0, 1, 5], [2, 4, 3, 6]]

In [4]:
data

[[1, 2, 3], [4, 5, 6, 7]]

In [5]:
st = time()

x = tf.dynamic_stitch(indices, data) 

print(f"Elapsed time: {time()-st: .2f} s")
print(f"x: {x}")
print(f"Shape of x: {x.shape}")
print(f"Type of x: {type(x)}")
print(f"Datatype of x: {x.dtype}")

Elapsed time:  48.60 s
x: [1 2 4 6 5 3 7]
Shape of x: (7,)
Type of x: <class 'tensorflow.python.framework.ops.EagerTensor'>
Datatype of x: <dtype: 'int32'>


## Example 2

In [6]:
import tensorflow as tf 

In [7]:
indices = [[0, 1, 2], [5, 4, 3]] 
data = [[1, 2, 3], [4, 5, 6]] 

In [8]:
indices

[[0, 1, 2], [5, 4, 3]]

In [9]:
data

[[1, 2, 3], [4, 5, 6]]

In [10]:
st = time()

x = tf.dynamic_stitch(indices, data) 

print(f"Elapsed time: {time()-st: .2f} s")
print(f"x: {x}")
print(f"Shape of x: {x.shape}")
print(f"Type of x: {type(x)}")
print(f"Datatype of x: {x.dtype}")

Elapsed time:  0.00 s
x: [1 2 3 6 5 4]
Shape of x: (6,)
Type of x: <class 'tensorflow.python.framework.ops.EagerTensor'>
Datatype of x: <dtype: 'int32'>


## Example 3

https://www.tensorflow.org/api_docs/python/tf/dynamic_stitch

In [11]:
import tensorflow as tf 

In [12]:
# Apply function (increments x_i) on elements for which a certain condition
# apply (x_i != -1 in this example).
x=tf.constant([0.1, -1., 5.2, 4.3, -1., 7.4])
x

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0.1, -1. ,  5.2,  4.3, -1. ,  7.4], dtype=float32)>

In [13]:
condition_mask=tf.not_equal(x,tf.constant(-1.))
condition_mask

<tf.Tensor: shape=(6,), dtype=bool, numpy=array([ True, False,  True,  True, False,  True])>

In [14]:
tf.cast(condition_mask, tf.int32)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 0, 1, 1, 0, 1])>

In [15]:
partitioned_data = tf.dynamic_partition(x, tf.cast(condition_mask, tf.int32) , 2)
partitioned_data

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1., -1.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.1, 5.2, 4.3, 7.4], dtype=float32)>]

In [16]:
partitioned_data[1] = partitioned_data[1] + 1.0
partitioned_data

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1., -1.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 6.2, 5.3, 8.4], dtype=float32)>]

In [17]:
tf.range(tf.shape(x)[0])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [18]:
tf.range(x.shape[0]) # equivalent

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [19]:
tf.cast(condition_mask, tf.int32)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 0, 1, 1, 0, 1])>

In [20]:
condition_indices = tf.dynamic_partition(tf.range(tf.shape(x)[0]), tf.cast(condition_mask, tf.int32) , 2)
condition_indices

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 2, 3, 5])>]

In [21]:
x = tf.dynamic_stitch(condition_indices, partitioned_data)
x
   
# Here x=[1.1, -1., 6.2, 5.3, -1, 8.4], the -1. values remain
# unchanged.

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 1.1, -1. ,  6.2,  5.3, -1. ,  8.4], dtype=float32)>